; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"
projects[drupal][type] = "core"

; Modules
projects[pathauto][version] = "1.3"

projects[webform][version] = "4.12"

projects[token][version] = "1.6"

projects[views][version] = "3.13"

projects[ctools][version] = "1.9"

projects[date][version] = "2.9"

projects[references][version] = "2.1"

projects[wysiwyg][version] = "2.2"

projects[masquerade][version] = "1.0-rc7"

projects[media][version] = "2.0-beta2"

projects[css_injector][version] = "1.10"

projects[styles][version] = "2.0-alpha8"

projects[ckeditor][version] = "1.17"

