; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[] = "drupal"
; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall][download][type] = ""
projects[kwall][download][url] = ""
projects[kwall][type] = "module"

projects[] = "absolute_messages"
projects[] = "views_bulk_operations"
projects[addressfield][subdir] = "contrib"

projects[addthis][subdir] = "contrib"

projects[addtocal][subdir] = "contrib"

projects[] = "admin_views"
projects[] = "advanced_help"
projects[] = "backports"
projects[] = "backup_migrate"
projects[bean][subdir] = "contrib"

projects[bean_entity_view][subdir] = "contrib"

projects[bean_tax][subdir] = "contrib"

projects[better_exposed_filters][subdir] = "contrib"

projects[bg_image][subdir] = "contrib"

projects[bg_image_formatter][subdir] = "contrib"

projects[] = "block_class"
projects[] = "ctools"
projects[calendar][subdir] = "contrib"

projects[] = "captcha"
projects[ckeditor][subdir] = "contrib"

projects[] = "ckeditor_filter"
projects[codefilter][subdir] = "contrib"

projects[] = "colorbox"
projects[context][subdir] = "contrib"

projects[] = "css_injector"
projects[] = "date"
projects[date_ical][subdir] = "contrib"

projects[] = "devel"
projects[] = "elements"
projects[] = "entity"
projects[entity_view_mode][subdir] = "contrib"

projects[] = "entityreference"
projects[] = "extlink"
projects[] = "favicon"
projects[] = "features"
projects[feeds][subdir] = "contrib"

projects[feeds_tamper][subdir] = "contrib"

projects[feeds_tamper_php][subdir] = "contrib"

projects[fences][patches][0] = "http://drupal.org/files/undefined-index-1561244-7.patch"

projects[field_collection][subdir] = "contrib"

projects[field_collection_tabs][subdir] = "contrib"

projects[] = "field_formatter_css_class"
projects[field_formatter_settings][subdir] = "contrib"

projects[] = "field_group"
projects[] = "file_entity"
projects[flexslider][subdir] = "contrib"

projects[] = "flood_control"
projects[focal_point][subdir] = "contrib"

projects[geofield][subdir] = "contrib"

projects[geophp][subdir] = "contrib"

projects[] = "globalredirect"
projects[gmap][subdir] = "contrib"

projects[google_appliance][subdir] = "contrib"

projects[google_analytics][subdir] = "contrib"

projects[] = "html5_tools"
projects[] = "imce"
projects[job_scheduler][subdir] = "contrib"

projects[] = "jquery_placeholder"
projects[] = "jquery_update"
projects[ldap][subdir] = "contrib"

projects[leaflet][subdir] = "contrib"

projects[] = "less"
projects[] = "libraries"
projects[link][subdir] = "contrib"

projects[linked_field][subdir] = "contrib"

projects[] = "logintoboggan"
projects[] = "mailsystem"
projects[] = "masquerade"
projects[menu_editor][subdir] = "contrib"

projects[] = "media"
projects[media_ckeditor][subdir] = "contrib"

projects[media_vimeo][subdir] = "contrib"

projects[media_youtube][subdir] = "contrib"

projects[menu_attributes][subdir] = "contrib"

projects[] = "menu_block"
projects[] = "menu_position"
projects[] = "metatag"
projects[migrate][subdir] = "contrib"

projects[] = "mimemail"
projects[] = "module_filter"
projects[] = "navbar"
projects[nodeaccess][subdir] = "contrib"

projects[nodequeue][subdir] = "contrib"

projects[oauth][subdir] = "contrib"

projects[og][subdir] = "contrib"

projects[] = "options_element"
projects[paragraphs][subdir] = "contrib"

projects[] = "pathauto"
projects[] = "pathologic"
projects[popup][subdir] = "contrib"

projects[popup_views_integration][subdir] = "contrib"

projects[protected_pages][subdir] = "contrib"

projects[quicktabs][subdir] = "contrib"

projects[] = "recaptcha"
projects[] = "redirect"
projects[] = "rules"
projects[] = "simplehtmldom"
projects[slick][subdir] = "contrib"

projects[slick_views][subdir] = "contrib"

projects[smart_trim][subdir] = "contrib"

projects[] = "smtp"
projects[social_content][subdir] = "contrib"

projects[speedboxes][subdir] = "contrib"

projects[] = "strongarm"
projects[] = "superfish"
projects[taxonomy_entity_index][subdir] = "contrib"

projects[] = "title"
projects[] = "token"
projects[] = "touch_icons"
projects[] = "transliteration"
projects[] = "variable"
projects[] = "variable_email"
projects[viewfield][patches][0] = "https://www.drupal.org/files/viewfield-token_dialog-1784880.patch"

projects[] = "views"
projects[] = "views_data_export"
projects[] = "views_php"
projects[] = "views_slideshow"
projects[void_menu][subdir] = "contrib"

projects[webform][subdir] = "contrib"

projects[workbench][subdir] = "contrib"

projects[workbench_moderation][subdir] = "contrib"

projects[wysiwyg_template][subdir] = "contrib"

projects[] = "xmlsitemap"
; Themes
projects[] = "ember"
projects[zen][subdir] = "contrib"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[addressfield_autocomplete][download][type] = ""
projects[addressfield_autocomplete][download][url] = ""
projects[addressfield_autocomplete][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall_accordion_menu][download][type] = ""
projects[kwall_accordion_menu][download][url] = ""
projects[kwall_accordion_menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall_bg_image_formatter][download][type] = ""
projects[kwall_bg_image_formatter][download][url] = ""
projects[kwall_bg_image_formatter][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall-gallery][download][type] = ""
projects[kwall-gallery][download][url] = ""
projects[kwall-gallery][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall-menu-mega][download][type] = ""
projects[kwall-menu-mega][download][url] = ""
projects[kwall-menu-mega][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall_migration][download][type] = ""
projects[kwall_migration][download][url] = ""
projects[kwall_migration][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[sonoma_slide_menu][download][type] = ""
projects[sonoma_slide_menu][download][url] = ""
projects[sonoma_slide_menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[responsive-menu][download][type] = ""
projects[responsive-menu][download][url] = ""
projects[responsive-menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[sonoma_social_stream][download][type] = ""
projects[sonoma_social_stream][download][url] = ""
projects[sonoma_social_stream][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ssuedu_custom][download][type] = ""
projects[ssuedu_custom][download][url] = ""
projects[ssuedu_custom][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ssuedu_migration][download][type] = ""
projects[ssuedu_migration][download][url] = ""
projects[ssuedu_migration][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall_ember][download][type] = ""
projects[kwall_ember][download][url] = ""
projects[kwall_ember][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ssuedu_child_theme][download][type] = ""
projects[ssuedu_child_theme][download][url] = ""
projects[ssuedu_child_theme][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ssuedu_child_theme_2][download][type] = ""
projects[ssuedu_child_theme_2][download][url] = ""
projects[ssuedu_child_theme_2][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ssuedu_theme][download][type] = ""
projects[ssuedu_theme][download][url] = ""
projects[ssuedu_theme][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.placeholder][download][type] = ""
libraries[jquery.placeholder][download][url] = ""
libraries[jquery.placeholder][directory_name] = "jquery.placeholder"
libraries[jquery.placeholder][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = ""
libraries[json2][download][url] = ""
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = ""
libraries[lessphp][download][url] = ""
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[simplehtmldom][download][type] = ""
libraries[simplehtmldom][download][url] = ""
libraries[simplehtmldom][directory_name] = "simplehtmldom"
libraries[simplehtmldom][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[Superfish][download][type] = ""
libraries[Superfish][download][url] = ""
libraries[Superfish][directory_name] = "Superfish"
libraries[Superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[flexslider][download][type] = ""
libraries[flexslider][download][url] = ""
libraries[flexslider][directory_name] = "flexslider"
libraries[flexslider][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[geocomplete][download][type] = ""
libraries[geocomplete][download][url] = ""
libraries[geocomplete][directory_name] = "geocomplete"
libraries[geocomplete][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[gridder][download][type] = ""
libraries[gridder][download][url] = ""
libraries[gridder][directory_name] = "gridder"
libraries[gridder][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[iCalcreator][download][type] = ""
libraries[iCalcreator][download][url] = ""
libraries[iCalcreator][directory_name] = "iCalcreator"
libraries[iCalcreator][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-placeholder-gh-pages][download][type] = ""
libraries[jquery-placeholder-gh-pages][download][url] = ""
libraries[jquery-placeholder-gh-pages][directory_name] = "jquery-placeholder-gh-pages"
libraries[jquery-placeholder-gh-pages][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[leaflet][download][type] = ""
libraries[leaflet][download][url] = ""
libraries[leaflet][directory_name] = "leaflet"
libraries[leaflet][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[select2][download][type] = ""
libraries[select2][download][url] = ""
libraries[select2][directory_name] = "select2"
libraries[select2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[slick][download][type] = ""
libraries[slick][download][url] = ""
libraries[slick][directory_name] = "slick"
libraries[slick][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[stacktable][download][type] = ""
libraries[stacktable][download][url] = ""
libraries[stacktable][directory_name] = "stacktable"
libraries[stacktable][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

