; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[drupal][version] = "7.43"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall][download][type] = ""
projects[kwall][download][url] = ""
projects[kwall][type] = "module"

projects[absolute_messages][version] = "1.3"

projects[views_bulk_operations][version] = "3.3"

projects[addressfield][subdir] = "contrib"
projects[addressfield][version] = "1.2"

projects[addthis][subdir] = "contrib"
projects[addthis][version] = "4.0-alpha6"

projects[addtocal][subdir] = "contrib"
projects[addtocal][version] = "1.0-beta3"

projects[admin_views][version] = "1.5"

projects[advanced_help][version] = "1.3+4-dev"

projects[backports][version] = "1.0-alpha1"

projects[backup_migrate][version] = "3.1"

projects[bean][subdir] = "contrib"
projects[bean][version] = "1.9"

projects[bean_entity_view][subdir] = "contrib"
projects[bean_entity_view][version] = "1.0-beta2"

projects[bean_tax][subdir] = "contrib"
projects[bean_tax][version] = "2.7"

projects[better_exposed_filters][subdir] = "contrib"
projects[better_exposed_filters][version] = "3.2"

projects[bg_image][subdir] = "contrib"
projects[bg_image][version] = "1.4"

projects[bg_image_formatter][subdir] = "contrib"
projects[bg_image_formatter][version] = "1.4"

projects[block_class][version] = "2.3"

projects[ctools][version] = "1.9"

projects[calendar][subdir] = "contrib"
projects[calendar][version] = "3.5"

projects[captcha][version] = "1.3"

projects[ckeditor][subdir] = "contrib"
projects[ckeditor][version] = "1.17"

projects[ckeditor_filter][version] = "1.2"

projects[codefilter][subdir] = "contrib"
projects[codefilter][version] = "1.2"

projects[colorbox][version] = "2.10"

projects[context][subdir] = "contrib"
projects[context][version] = "3.7"

projects[css_injector][version] = "1.10"

projects[date][version] = "2.9"

projects[date_ical][subdir] = "contrib"
projects[date_ical][version] = "3.9"

projects[devel][version] = "1.5"

projects[elements][version] = "1.4"

projects[entity][version] = "1.7"

projects[entity_view_mode][subdir] = "contrib"
projects[entity_view_mode][version] = "1.0-rc1"

projects[entityreference][version] = "1.1"

projects[extlink][version] = "1.18"

projects[favicon][version] = "2.1"

projects[features][version] = "2.8"

projects[feeds][subdir] = "contrib"
projects[feeds][version] = "2.0-beta2"

projects[feeds_tamper][subdir] = "contrib"
projects[feeds_tamper][version] = "1.1"

projects[feeds_tamper_php][subdir] = "contrib"
projects[feeds_tamper_php][version] = "1.2"

projects[fences][version] = "1.2"
projects[fences][patches][0] = "http://drupal.org/files/undefined-index-1561244-7.patch"

projects[field_collection][subdir] = "contrib"
projects[field_collection][version] = "1.0-beta11"

projects[field_collection_tabs][subdir] = "contrib"
projects[field_collection_tabs][version] = "1.1"

projects[field_formatter_css_class][version] = "1.3+5-dev"

projects[field_formatter_settings][subdir] = "contrib"
projects[field_formatter_settings][version] = "1.1"

projects[field_group][version] = "1.5"

projects[file_entity][version] = "2.0-beta2"

projects[flood_control][version] = "1.0"

projects[focal_point][subdir] = "contrib"
projects[focal_point][version] = "1.0-beta6"

projects[geofield][subdir] = "contrib"
projects[geofield][version] = "2.3"

projects[geophp][subdir] = "contrib"
projects[geophp][version] = "1.7"

projects[globalredirect][version] = "1.5"

projects[gmap][subdir] = "contrib"
projects[gmap][version] = "2.11"

projects[google_appliance][subdir] = "contrib"
projects[google_appliance][version] = "1.14"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "2.1"

projects[html5_tools][version] = "1.3"

projects[imce][version] = "1.10"

projects[job_scheduler][subdir] = "contrib"
projects[job_scheduler][version] = "2.0-alpha3"

projects[jquery_placeholder][version] = "1.0-beta2"

projects[jquery_update][version] = "2.7"

projects[leaflet][subdir] = "contrib"
projects[leaflet][version] = "1.3"

projects[less][version] = "3.0"

projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.4"

projects[linked_field][subdir] = "contrib"
projects[linked_field][version] = "1.10"

projects[logintoboggan][version] = "1.5"

projects[mailsystem][version] = "2.34"

projects[masquerade][version] = "1.0-rc7"

projects[menu_editor][subdir] = "contrib"
projects[menu_editor][version] = "1.0-beta3"

projects[media][version] = "2.0-beta1"

projects[media_ckeditor][subdir] = "contrib"
projects[media_ckeditor][version] = "2.0-alpha1"

projects[media_vimeo][subdir] = "contrib"
projects[media_vimeo][version] = "2.1"

projects[media_youtube][subdir] = "contrib"
projects[media_youtube][version] = "3.0"

projects[menu_attributes][subdir] = "contrib"
projects[menu_attributes][version] = "1.0"

projects[menu_block][version] = "2.7"

projects[menu_position][version] = "1.2"

projects[metatag][version] = "1.14"

projects[mimemail][version] = "1.0-beta4"

projects[module_filter][version] = "2.0"

projects[navbar][version] = "1.7"

projects[nodeaccess][subdir] = "contrib"
projects[nodeaccess][version] = "1.4"

projects[oauth][subdir] = "contrib"
projects[oauth][version] = "3.2"

projects[og][subdir] = "contrib"
projects[og][version] = "2.8"

projects[options_element][version] = "1.12"

projects[paragraphs][subdir] = "contrib"
projects[paragraphs][version] = "1.0-rc4"

projects[pathauto][version] = "1.3"

projects[pathologic][version] = "3.1"

projects[protected_pages][subdir] = "contrib"
projects[protected_pages][version] = "2.4"

projects[quicktabs][subdir] = "contrib"
projects[quicktabs][version] = "3.6"

projects[recaptcha][version] = "2.0"

projects[redirect][version] = "1.0-rc3"

projects[rules][version] = "2.9"

projects[simplehtmldom][version] = "2.1"

projects[slick][subdir] = "contrib"
projects[slick][version] = "2.0"

projects[slick_views][subdir] = "contrib"
projects[slick_views][version] = "2.0"

projects[smtp][version] = "1.3"

projects[social_content][subdir] = "contrib"
projects[social_content][version] = "2.0-beta7+3-dev"

projects[speedboxes][subdir] = "contrib"
projects[speedboxes][version] = "1.3"

projects[strongarm][version] = "2.0"

projects[superfish][version] = "1.9+41-dev"

projects[taxonomy_entity_index][subdir] = "contrib"
projects[taxonomy_entity_index][version] = "1.0-beta7"

projects[title][version] = "1.0-alpha8"

projects[token][version] = "1.6"

projects[touch_icons][version] = "1.0"

projects[transliteration][version] = "3.2"

projects[variable][version] = "2.5"

projects[variable_email][version] = "1.0-alpha1"

projects[viewfield][version] = "2.0"
projects[viewfield][patches][0] = "https://www.drupal.org/files/viewfield-token_dialog-1784880.patch"

projects[views][version] = "3.13"

projects[views_data_export][version] = "3.0-beta9"

projects[views_php][version] = "1.0-alpha3"

projects[views_slideshow][version] = "3.1"

projects[void_menu][subdir] = "contrib"
projects[void_menu][version] = "1.9"

projects[webform][subdir] = "contrib"
projects[webform][version] = "4.12"

projects[workbench][subdir] = "contrib"
projects[workbench][version] = "1.2"

projects[workbench_moderation][subdir] = "contrib"
projects[workbench_moderation][version] = "1.4"

projects[wysiwyg_template][subdir] = "contrib"
projects[wysiwyg_template][version] = "2.12"

projects[xmlsitemap][version] = "2.2"

; Themes
projects[ember][version] = "2.0-alpha4"

projects[zen][subdir] = "contrib"
projects[zen][version] = "5.6"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[addressfield_autocomplete][download][type] = ""
projects[addressfield_autocomplete][download][url] = ""
projects[addressfield_autocomplete][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall_accordion_menu][download][type] = ""
projects[kwall_accordion_menu][download][url] = ""
projects[kwall_accordion_menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall-gallery][download][type] = ""
projects[kwall-gallery][download][url] = ""
projects[kwall-gallery][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall-menu-mega][download][type] = ""
projects[kwall-menu-mega][download][url] = ""
projects[kwall-menu-mega][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[sonoma_slide_menu][download][type] = ""
projects[sonoma_slide_menu][download][url] = ""
projects[sonoma_slide_menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[responsive-menu][download][type] = ""
projects[responsive-menu][download][url] = ""
projects[responsive-menu][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[sonoma_social_stream][download][type] = ""
projects[sonoma_social_stream][download][url] = ""
projects[sonoma_social_stream][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ssuedu_custom][download][type] = ""
projects[ssuedu_custom][download][url] = ""
projects[ssuedu_custom][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ssuedu_migration][download][type] = ""
projects[ssuedu_migration][download][url] = ""
projects[ssuedu_migration][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[kwall_ember][download][type] = ""
projects[kwall_ember][download][url] = ""
projects[kwall_ember][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ssuedu_theme][download][type] = ""
projects[ssuedu_theme][download][url] = ""
projects[ssuedu_theme][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[simplehtmldom][download][type] = ""
libraries[simplehtmldom][download][url] = ""
libraries[simplehtmldom][directory_name] = "simplehtmldom"
libraries[simplehtmldom][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[lessphp][download][type] = ""
libraries[lessphp][download][url] = ""
libraries[lessphp][directory_name] = "lessphp"
libraries[lessphp][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.placeholder][download][type] = ""
libraries[jquery.placeholder][download][url] = ""
libraries[jquery.placeholder][directory_name] = "jquery.placeholder"
libraries[jquery.placeholder][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[colorbox][download][type] = ""
libraries[colorbox][download][url] = ""
libraries[colorbox][directory_name] = "colorbox"
libraries[colorbox][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[json2][download][type] = ""
libraries[json2][download][url] = ""
libraries[json2][directory_name] = "json2"
libraries[json2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[superfish][download][type] = ""
libraries[superfish][download][url] = ""
libraries[superfish][directory_name] = "superfish"
libraries[superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[select2][download][type] = ""
libraries[select2][download][url] = ""
libraries[select2][directory_name] = "select2"
libraries[select2][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[geocomplete][download][type] = ""
libraries[geocomplete][download][url] = ""
libraries[geocomplete][directory_name] = "geocomplete"
libraries[geocomplete][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[slick][download][type] = ""
libraries[slick][download][url] = ""
libraries[slick][directory_name] = "slick"
libraries[slick][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[iCalcreator][download][type] = ""
libraries[iCalcreator][download][url] = ""
libraries[iCalcreator][directory_name] = "iCalcreator"
libraries[iCalcreator][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[gridder][download][type] = ""
libraries[gridder][download][url] = ""
libraries[gridder][directory_name] = "gridder"
libraries[gridder][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery-placeholder-gh-pages][download][type] = ""
libraries[jquery-placeholder-gh-pages][download][url] = ""
libraries[jquery-placeholder-gh-pages][directory_name] = "jquery-placeholder-gh-pages"
libraries[jquery-placeholder-gh-pages][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[Superfish][download][type] = ""
libraries[Superfish][download][url] = ""
libraries[Superfish][directory_name] = "Superfish"
libraries[Superfish][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = ""
libraries[modernizr][download][url] = ""
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[leaflet][download][type] = ""
libraries[leaflet][download][url] = ""
libraries[leaflet][directory_name] = "leaflet"
libraries[leaflet][type] = "library"

