; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.30"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[panopoly][download][type] = ""
projects[panopoly][download][url] = ""
projects[panopoly][type] = "module"
projects[panopoly][version] = "1.9"

projects[views_bulk_operations][version] = "3.2"

projects[admin_views][version] = "1.3"

projects[apps][version] = "1.0-beta7+15-dev"
projects[apps][patches][] = "http://drupal.org/files/1790902.4-check-last-modified-existing.patch"

projects[backports][version] = "1.0-alpha1"

projects[breakpoints][version] = "1.2"

projects[ctools][version] = "1.4"
projects[ctools][patches][] = "http://drupal.org/files/issues/ctools-views-pane-more-link-2312505-1.patch"

projects[caption_filter][version] = "1.2+9-dev"

projects[cas][version] = "1.4"

projects[cas_attributes][version] = "1.0-rc3"

projects[facetapi][version] = "1.3"

projects[date][version] = "2.8"

projects[date_popup_authored][version] = "1.1+2-dev"

projects[defaultconfig][version] = "1.0-alpha9"
projects[defaultconfig][patches][] = "http://drupal.org/files/fix-defaultconfig_rebuild_all.patch"

projects[devel][version] = "1.5"

projects[entity][version] = "1.5"

projects[entityreference][version] = "1.1"

projects[fape][version] = "1.2"

projects[features][version] = "2.0"

projects[field_group][version] = "1.4"

projects[fieldable_panels_panes][version] = "1.5"
projects[fieldable_panels_panes][patches][] = "http://drupal.org/files/issues/fieldable_panels_panes-n2283263-5.patch"

projects[file_entity][version] = "2.0-alpha3+29-dev"

projects[panels][version] = "3.4"
projects[panels][patches][] = "http://drupal.org/files/issues/panels-ipe-keyboard-focus-2280797-2.patch"

projects[image_resize_filter][version] = "1.14"

projects[jquery_update][version] = "2.3"

projects[ldap][version] = "2.0-beta8"

projects[libraries][version] = "2.2"

projects[link][version] = "1.2"

projects[linkit][version] = "3.2"

projects[manualcrop][version] = "1.4+109-dev"
projects[manualcrop][patches][] = "http://drupal.org/files/issues/manualcrop-make-file-2248587.patch"

projects[media][version] = "2.0-alpha3+98-dev"
projects[media][patches][] = "http://drupal.org/files/issues/media-alt-title-double-encoded-2308487-1.patch"

projects[media_vimeo][version] = "2.0"

projects[media_youtube][version] = "2.0-rc4+9-dev"

projects[menu_block][version] = "2.4"

projects[migrate][version] = "2.5"

projects[module_filter][version] = "1.8"

projects[navbar][version] = "1.0-alpha10+8-dev"
projects[navbar][patches][] = "http://drupal.org/files/z-index-heart-cools-2050559-1.patch"

projects[panelizer][version] = "3.1"

projects[panels_breadcrumbs][version] = "2.1"

projects[panopoly_admin][version] = "1.9"

projects[panopoly_core][version] = "1.10"

projects[panopoly_demo][version] = "1.9"

projects[panopoly_images][version] = "1.9"

projects[panopoly_magic][version] = "1.9"

projects[panopoly_pages][version] = "1.10"

projects[panopoly_search][version] = "1.9"

projects[panopoly_theme][version] = "1.9"

projects[panopoly_users][version] = "1.9"

projects[panopoly_widgets][version] = "1.9"

projects[panopoly_wysiwyg][version] = "1.9"

projects[pathauto][version] = "1.2"
projects[pathauto][patches][] = "http://drupal.org/files/issues/pathauto-persist-936222-195-pathauto-state.patch"

projects[pm_existing_pages][version] = "1.4"

projects[save_draft][version] = "1.4"

projects[search_api][version] = "1.13"

projects[search_api_db][version] = "1.0-rc2"

projects[search_api_solr][version] = "1.1"

projects[simple_gmap][version] = "1.2"

projects[simplified_menu_admin][version] = "1.0-beta2"

projects[strongarm][version] = "2.0"

projects[tablefield][version] = "2.2"
projects[tablefield][patches][] = "http://drupal.org/files/tablefield_event_click_conflict.patch"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.2"

projects[user_picture_field][version] = "1.0-rc1"

projects[uuid][version] = "1.0-alpha5"

projects[views][version] = "3.8"
projects[views][patches][] = "http://drupal.org/files/views-exposed-sorts-2037469-1.patch"

projects[views_autocomplete_filters][version] = "1.1"
projects[views_autocomplete_filters][patches][] = "http://drupal.org/files/issues/ViewsAutocompleteFilters-no_results_on_some_environments-2277453-1.patch"

projects[wysiwyg][version] = "2.2"
projects[wysiwyg][patches][] = "http://drupal.org/files/wysiwyg-1802394-4.patch"

projects[wysiwyg_filter][version] = "1.6-rc2"

; Themes
projects[responsive_bartik][version] = "1.0-rc1"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[SolrPhpClient][download][type] = ""
libraries[SolrPhpClient][download][url] = ""
libraries[SolrPhpClient][directory_name] = "SolrPhpClient"
libraries[SolrPhpClient][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = ""
libraries[underscore][download][url] = ""
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = ""
libraries[backbone][download][url] = ""
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imagesloaded][download][type] = ""
libraries[jquery.imagesloaded][download][url] = ""
libraries[jquery.imagesloaded][directory_name] = "jquery.imagesloaded"
libraries[jquery.imagesloaded][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[respondjs][download][type] = ""
libraries[respondjs][download][url] = ""
libraries[respondjs][directory_name] = "respondjs"
libraries[respondjs][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imgareaselect][download][type] = ""
libraries[jquery.imgareaselect][download][url] = ""
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[markitup][download][type] = ""
libraries[markitup][download][url] = ""
libraries[markitup][directory_name] = "markitup"
libraries[markitup][type] = "library"

