; This file was auto-generated by drush make
core = 7.x
api = 2

; Core
projects[panopoly][type] = "core"
projects[panopoly][version] = "7.x-1.30"

; Modules
projects[addressfield][version] = "1.2"

projects[advanced_help][version] = "1.3"

projects[backup_migrate][version] = "3.1"

projects[calendar][version] = "3.5"

projects[cas][version] = "1.4"

projects[email][version] = "1.3"

projects[entityreference_prepopulate][version] = "1.6"

projects[entity_view_mode][version] = "1.0-rc1"

projects[facetapi][version] = "1.5"

projects[feeds][version] = "2.0-beta1"

projects[feeds_tamper][version] = "1.1"

projects[field_permissions][version] = "1.0-beta2"

projects[geocoder][version] = "1.3"

projects[geofield][version] = "2.3"

projects[geophp][version] = "1.7"

projects[google_analytics][version] = "2.1"

projects[highcharts][version] = "1.0-alpha6"

projects[job_scheduler][version] = "2.0-alpha3"

projects[ldap][version] = "2.0-beta8"

projects[leaflet][version] = "1.3"

projects[leaflet_more_maps][version] = "1.14"

projects[masquerade][version] = "1.0-rc7"

projects[message][version] = "1.11"

projects[message_notify][version] = "2.5"

projects[node_limit][version] = "1.0-alpha5"

projects[office_hours][version] = "1.4"

projects[og][version] = "2.7"

projects[og_fpp][version] = "1.0-alpha1"

projects[opening_hours][version] = "1.5"

projects[registration][version] = "1.6"

projects[roleassign][version] = "1.0"

projects[rules][version] = "2.9"

projects[securelogin][version] = "1.6"

projects[semanticviews][version] = "1.0-rc2"

projects[simple_ldap][version] = "1.4"

projects[taxonomy_menu][version] = "1.5"

projects[tipsy][version] = "1.0-rc1"

projects[video_embed_field][version] = "2.0-beta11"

projects[webform][version] = "4.12"

projects[workbench][version] = "1.2"

projects[workbench_access][version] = "1.4"

projects[workbench_moderation][version] = "1.4"

projects[xmlsitemap][version] = "2.2"

; Libraries
libraries[highcharts][download][type] = "file"
libraries[highcharts][download][url] = "http://code.highcharts.com/zips/Highcharts-4.1.7.zip"
libraries[highcharts][type] = "library"

libraries[leaflet][download][type] = "file"
libraries[leaflet][download][url] = "http://cdn.leafletjs.com/downloads/leaflet-0.7.3.zip"
libraries[leaflet][type] = "library"

