; This file was auto-generated by drush make
; And then hand-edited by Eric to update to all the right things...
core = 7.x

api = 2
projects[drupal][version] = "7.34"

projects[panopoly][download][type] = "git"
projects[panopoly][type] = "profile"
projects[panopoly][version] = "1.14"

projects[cas][version] = "1.4"

projects[cas_attributes][version] = "1.0-rc3"

projects[ldap][version] = "2.0-beta8"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.imgareaselect][download][type] = ""
libraries[jquery.imgareaselect][download][url] = ""
libraries[jquery.imgareaselect][directory_name] = "jquery.imgareaselect"
libraries[jquery.imgareaselect][type] = "library"
