; This file was auto-generated by drush make
core = 
api = 2

; Core
; Libraries
libraries[leaflet][download][type] = "file"
libraries[leaflet][download][url] = "http://cdn.leafletjs.com/downloads/leaflet-0.7.3.zip"
libraries[leaflet][type] = "library"

